// import Image from 'next/image'
import Head from 'next/head'

import HeroComponent from '~/components/Hero'
import About from '~/components/About'
import FeaturedProduct from '~/components/Featured'

function Home() {
  return (
    <div>
      <Head>
        <title>AgCera Nutrition: Transforming Lives</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <HeroComponent />
      </div>

      <div>
        <About />
        <FeaturedProduct />
      </div>
    </div>
  )
}

export default Home
