// import Image from 'next/image'
import Head from 'next/head'

import Header from '~/components/Header'
import HeroComponent from '~/components/Hero'
import About from '~/components/About'
import FeaturedProduct from '~/components/Featured'
import Footer from '~/components/Footer'

function Home() {
  return (
    <div>
      <Head>
        <title>AgCera Nutrition: Transforming Lives</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='py-5'>
        <Header />
      </div>
      <div>
        <HeroComponent />
      </div>

      <main>
        <About />
        <FeaturedProduct />
        <Footer />
      </main>
    </div>
  )
}

export default Home
